name: Generate profile README periodically

on:
  # Trigger this workflow every other hour...
  schedule:
    - cron: '0 */2 * * *'
  
  # ...or manually by pressing a button
  workflow_dispatch: 

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # Check out the template repository
      - uses: actions/checkout@v2
        with:
          ref: template

      - name: Run the generator script
        run: ./generate.sh "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
