name: Update profile README

on:
  # Trigger this workflow twice a day...
  schedule:
    - cron: '0 0,12 * * *'
  
  # ...or manually by pressing a button...
  workflow_dispatch: 

  # ...or whenever other workflow calls this
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout template
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Run the generator script
        run: make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          METRICS_GITHUB_TOKEN: ${{ secrets.METRICS_GITHUB_TOKEN }}
