name: Update profile README

on:
  # Trigger this workflow every hour...
  # schedule:
  #  - cron: '0 * * * *'
  
  # ...or manually by pressing a button...
  workflow_dispatch: 

  # ...or whenever other workflow calls this
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout template
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Run the generator script
        run: make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
